name: Ubuntu 18.04

on:
  push:
  pull_request:
  release:
    types: [published]
  schedule:
    - cron: '30 3 * * 0'

jobs:
  build-ubuntu16:
    name: Ubuntu 18.04
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Build
        id: build
        env:
          TAG: ${{ github.ref }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          BOOST_ROOT=
          sudo apt install -y libboost-all-dev
          build_folder="build/release"
          if [[ "${TAG:5:4}" == "tags" ]]; then export TAG=${TAG:10}; else export TAG=${COMMIT_SHA::8}; fi
          $krb_ver=${TAG}
          krb_ver_folder=$(echo $krb_ver | sed 's/\.//g')
          release_name=Karbo-cli-ubuntu18.04-v"$krb_ver"
          mkdir -p "$build_folder"
          cd "$build_folder"
          cmake -D CMAKE_BUILD_TYPE=Release ../..
          make
          mkdir -p "$release_name/$krb_ver_folder"
          exeFiles=()
          for f in src/*; do [[ -x $f && -f $f ]] && exeFiles+=( "$f" ); done
          cp "${exeFiles[@]}" "$release_name/$krb_ver_folder"
          cd "$release_name"
          tar -czf "$release_name".tar.gz "$krb_ver_folder"
          sha256=$(shasum -a 256 "$release_name".tar.gz | awk '{print toupper($1)}')
          asset_path="./$build_folder/$release_name/$release_name.tar.gz"
          echo "::set-output name=sha256::${sha256}"
          echo "::set-output name=release_name::${release_name}.tar.gz"
          echo "::set-output name=asset_path::${asset_path}"
          echo "::set-output name=krb_ver::${krb_ver}"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.build.outputs.asset_path }}
          name: Karbo CLI Suite v${{ steps.build.outputs.krb_ver }}
          body: |
            **${{ steps.build.outputs.release_name }}**
            ${{ steps.build.outputs.sha256 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload To GH Artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ${{ steps.build.outputs.release_name }}
          path: ${{ steps.build.outputs.asset_path }}
